# Generated by Django 5.1.4 on 2024-12-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Price', models.FloatField(default=0)),
                ('Ingredients', models.CharField(max_length=400)),
                ('Vegetarian', models.BooleanField(default=False)),
            ],
        ),
    ]
